// Preload script runs in a context that has access to both
// the DOM and Node.js APIs, but cannot directly access the main process
// This is a security best practice in Electron

const { contextBridge, ipcRenderer } = require('electron');

// Expose protected methods that allow the renderer process to use
// the APIs you need. This is where you can add custom APIs
contextBridge.exposeInMainWorld('electronAPI', {
  gitClone: (url, path) => ipcRenderer.invoke('git:clone', url, path),
  gitOpen: (path) => ipcRenderer.invoke('git:open', path),
  gitStatus: () => ipcRenderer.invoke('git:status'),
  gitStage: (files) => ipcRenderer.invoke('git:stage', files),
  gitUnstage: (files) => ipcRenderer.invoke('git:unstage', files),
  gitStageAll: () => ipcRenderer.invoke('git:stageAll'),
  gitUnstageAll: () => ipcRenderer.invoke('git:unstageAll'),
  gitCommit: (message, amend) => ipcRenderer.invoke('git:commit', message, amend),
  gitGenerateCommitMessage: () => ipcRenderer.invoke('git:generateCommitMessage'),
  gitGenerateConflictResolution: (filePath) => ipcRenderer.invoke('git:generateConflictResolution', filePath),
  gitApplyConflictResolution: (filePath, resolvedCode) => ipcRenderer.invoke('git:applyConflictResolution', filePath, resolvedCode),
  gitUndoCommit: () => ipcRenderer.invoke('git:undoCommit'),
  gitPush: (remote, branch, force, overwrite) => ipcRenderer.invoke('git:push', remote, branch, force, overwrite),
  gitPull: (remote, branch, targetBranch) => ipcRenderer.invoke('git:pull', remote, branch, targetBranch),
  gitAddRemote: (name, url) => ipcRenderer.invoke('git:addRemote', name, url),
  gitCreateGitHubRepo: (token, name, isPrivate, description) => ipcRenderer.invoke('git:createGitHubRepo', token, name, isPrivate, description),
  gitGetBranchStatus: () => ipcRenderer.invoke('git:getBranchStatus'),
  gitGetCurrentBranch: () => ipcRenderer.invoke('git:getCurrentBranch'),
  gitGetHistory: (maxCount, filters) => ipcRenderer.invoke('git:getHistory', maxCount, filters),
  getStashes: () => ipcRenderer.invoke('git:getStashes'),
  createStash: () => ipcRenderer.invoke('git:createStash'),
  applyStash: (name) => ipcRenderer.invoke('git:applyStash', name),
  deleteStash: (name) => ipcRenderer.invoke('git:deleteStash', name),
  gitGetBranchesDetailed: () => ipcRenderer.invoke('git:getBranchesDetailed'),
  gitFetch: (remote) => ipcRenderer.invoke('git:fetch', remote),
  gitFetchAll: () => ipcRenderer.invoke('git:fetchAll'),
  gitGetBranches: () => ipcRenderer.invoke('git:getBranches'),
  gitCreateBranch: (name, checkout) => ipcRenderer.invoke('git:createBranch', name, checkout),
  gitCheckoutBranch: (name) => ipcRenderer.invoke('git:checkoutBranch', name),
  gitGetBranchHeadIndex: (name) => ipcRenderer.invoke('git:getBranchHeadIndex', name),
  gitMergeBranchToCurrent: (branchToMerge) => ipcRenderer.invoke('git:mergeBranchToCurrent', branchToMerge),
  getRepoPath: () => ipcRenderer.invoke('git:getRepoPath'),
  getSuperprojectPath: () => ipcRenderer.invoke('git:getSuperprojectPath'),
  getRepoName: () => ipcRenderer.invoke('git:getRepoName'),
  getFilesChurn: (limit) => ipcRenderer.invoke('git:getFilesChurn', limit),
  getCommitActivity: () => ipcRenderer.invoke('git:getCommitActivity'),
  getTopContributors: (limit) => ipcRenderer.invoke('git:getTopContributors', limit),
  getCodebaseGrowth: () => ipcRenderer.invoke('git:getCodebaseGrowth'),
  getFileTypeDistribution: () => ipcRenderer.invoke('git:getFileTypeDistribution'),
  getRemoteUrl: (remote) => ipcRenderer.invoke('git:getRemoteUrl', remote),
  setRemoteUrl: (remote, url) => ipcRenderer.invoke('git:setRemoteUrl', remote, url),
  getRemoteBranches: () => ipcRenderer.invoke('git:getRemoteBranches'),
  getTags: () => ipcRenderer.invoke('git:getTags'),
  getCommitDiff: (commitHash) => ipcRenderer.invoke('git:getCommitDiff', commitHash),
  gitGetBranchDiff: (branchName) => ipcRenderer.invoke('git:getBranchDiff', branchName),
  gitGetAIBranchReview: (branchName) => ipcRenderer.invoke('git:getAIBranchReview', branchName),
  getFileDiff: (filePath, staged) => ipcRenderer.invoke('git:getFileDiff', filePath, staged),
  getFileBlame: (filePath, commitHash) => ipcRenderer.invoke('git:getFileBlame', filePath, commitHash),
  deleteBranch: (branchName, force) => ipcRenderer.invoke('git:deleteBranch', branchName, force),
  renameBranch: (oldName, newName) => ipcRenderer.invoke('git:renameBranch', oldName, newName),
  deleteRemoteBranch: (remoteBranchName) => ipcRenderer.invoke('git:deleteRemoteBranch', remoteBranchName),
  deleteTag: (tagName) => ipcRenderer.invoke('git:deleteTag', tagName),
  createTag: (name, commitHash) => ipcRenderer.invoke('git:createTag', name, commitHash),
  pushTag: (tagName, remote) => ipcRenderer.invoke('git:pushTag', tagName, remote),
  getRemoteTags: (remote) => ipcRenderer.invoke('git:getRemoteTags', remote),
  revertFileChanges: (filePath) => ipcRenderer.invoke('git:revertFileChanges', filePath),
  applyPatch: (patch, options) => ipcRenderer.invoke('git:applyPatch', patch, options),
  deleteFile: (filePath) => ipcRenderer.invoke('git:deleteFile', filePath),
  getTagsForCommit: (commitHash) => ipcRenderer.invoke('git:getTagsForCommit', commitHash),
  hasUnpushedCommits: () => ipcRenderer.invoke('git:hasUnpushedCommits'),
  testGitCredentials: (remoteUrl) => ipcRenderer.invoke('git:testGitCredentials', remoteUrl),
  getGitUserConfig: () => ipcRenderer.invoke('git:getGitUserConfig'),
  setGitUserConfig: (name, email, isGlobal) => ipcRenderer.invoke('git:setGitUserConfig', name, email, isGlobal),
  getConflictedFiles: () => ipcRenderer.invoke('git:getConflictedFiles'),
  resolveConflict: (filePath, decision) => ipcRenderer.invoke('git:resolveConflict', filePath, decision),
  abortMerge: () => ipcRenderer.invoke('git:abortMerge'),
  abortConflict: () => ipcRenderer.invoke('git:abortConflict'),
  openFileInMergeTool: (filePath) => ipcRenderer.invoke('git:openFileInMergeTool', filePath),
  openFileInDefaultEditor: (filePath) => ipcRenderer.invoke('git:openFileInDefaultEditor', filePath),
  gitRebaseBranch: (branch) => ipcRenderer.invoke('git:rebaseBranch', branch),
  gitAbortRebase: () => ipcRenderer.invoke('git:abortRebase'),
  gitContinueRebase: () => ipcRenderer.invoke('git:continueRebase'),
  gitRevertCommit: (commitHash) => ipcRenderer.invoke('git:revertCommit', commitHash),
  gitResetCommits: (commitHash, mode) => ipcRenderer.invoke('git:resetCommits', commitHash, mode),
  gitGetRevertStatus: () => ipcRenderer.invoke('git:getRevertStatus'),
  gitAbortRevert: () => ipcRenderer.invoke('git:abortRevert'),
  gitContinueRevert: () => ipcRenderer.invoke('git:continueRevert'),
  gitGetRebaseStatus: () => ipcRenderer.invoke('git:getRebaseStatus'),
  gitCherryPick: (commitHash) => ipcRenderer.invoke('git:cherryPick', commitHash),
  gitAbortCherryPick: () => ipcRenderer.invoke('git:abortCherryPick'),
  gitContinueCherryPick: () => ipcRenderer.invoke('git:continueCherryPick'),
  gitSkipCherryPick: () => ipcRenderer.invoke('git:skipCherryPick'),
  gitGetCherryPickStatus: () => ipcRenderer.invoke('git:getCherryPickStatus'),
  gitGetCommitsForInteractiveRebase: (targetBranch) => ipcRenderer.invoke('git:getCommitsForInteractiveRebase', targetBranch),
  gitInteractiveRebase: (targetBranch, todoLines) => ipcRenderer.invoke('git:performInteractiveRebase', targetBranch, todoLines),
  gitCancelOperation: () => ipcRenderer.invoke('git:cancelOperation'),
  openTerminal: () => ipcRenderer.invoke('git:openTerminal'),
  checkGitFlowInitialized: () => ipcRenderer.invoke('git:checkGitFlowInitialized'),
  initializeGitFlow: () => ipcRenderer.invoke('git:initializeGitFlow'),
  startGitFlowBranch: (type, name) => ipcRenderer.invoke('git:startGitFlowBranch', type, name),
  finishGitFlowBranch: (type, name) => ipcRenderer.invoke('git:finishGitFlowBranch', type, name),
  getSubmodules: () => ipcRenderer.invoke('git:getSubmodules'),
  addSubmodule: (url, path, applyConfigs) => ipcRenderer.invoke('git:addSubmodule', url, path, applyConfigs),
  updateSubmodules: () => ipcRenderer.invoke('git:updateSubmodules'),
  removeSubmodule: (path) => ipcRenderer.invoke('git:removeSubmodule', path),
  showOpenDialog: (options) => ipcRenderer.invoke('dialog:showOpenDialog', options),
  getRecentRepos: () => ipcRenderer.invoke('repos:getRecent'),
  addRecentRepo: (path) => ipcRenderer.invoke('repos:addRecent', path),
  removeRecentRepo: (path) => ipcRenderer.invoke('repos:removeRecent', path),
  getMergeToolPath: () => ipcRenderer.invoke('settings:getMergeToolPath'),
  setMergeToolPath: (path) => ipcRenderer.invoke('settings:setMergeToolPath', path),
  getMaxCommits: () => ipcRenderer.invoke('settings:getMaxCommits'),
  setMaxCommits: (maxCommits) => ipcRenderer.invoke('settings:setMaxCommits', maxCommits),
  getTheme: () => ipcRenderer.invoke('settings:getTheme'),
  setTheme: (theme) => ipcRenderer.invoke('settings:setTheme', theme),
  getAIProvider: () => ipcRenderer.invoke('settings:getAIProvider'),
  setAIProvider: (provider) => ipcRenderer.invoke('settings:setAIProvider', provider),
  getOllamaModel: () => ipcRenderer.invoke('settings:getOllamaModel'),
  setOllamaModel: (model) => ipcRenderer.invoke('settings:setOllamaModel', model),
  getOllamaHost: () => ipcRenderer.invoke('settings:getOllamaHost'),
  setOllamaHost: (host) => ipcRenderer.invoke('settings:setOllamaHost', host),
  gitGetOllamaModels: () => ipcRenderer.invoke('git:getOllamaModels'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  onShowShortcuts: (callback) => {
    const sub = () => callback();
    ipcRenderer.on('menu:show-shortcuts', sub);
    return () => ipcRenderer.removeListener('menu:show-shortcuts', sub);
  },
  onThemeChanged: (callback) => {
    const sub = (_, theme) => callback(theme);
    ipcRenderer.on('menu:theme-changed', sub);
    return () => ipcRenderer.removeListener('menu:theme-changed', sub);
  },
  onUpdateAvailable: (callback) => {
    const sub = (_, updateInfo) => callback(updateInfo);
    ipcRenderer.on('app:update-available', sub);
    return () => ipcRenderer.removeListener('app:update-available', sub);
  },
  onRepoChanged: (callback) => {
    const sub = (_, data) => callback(data);
    ipcRenderer.on('git:repo-changed', sub);
    return () => ipcRenderer.removeListener('git:repo-changed', sub);
  },
});
